package modelo;

public enum CantoJuego {
	VACIO, ENVIDO,REALENVIDO,FALTAENVIDO, ENVIDOX2, ENVIDOREALENVIDO, ENVIDOFALTAENVIDO, REALENVIDOFALTAENVIDO, 
	ENVIDOX2REALENVIDO, ENVIDOX2REALENVIDOFALTAENVIDO, ENVIDOREALENVIDOFALTAENVIDO, TRUCO, RETRUCO, VALECUATRO, 
	FLOR,CONTRAFLOR, CONTRAFLORALRESTO, ACEPTO, NOACEPTO, FINCANTO
}
